# frozen_string_literal: true

require "spec_helper"
require "tmpdir"

RSpec.describe AutoDoc::Generator::AgentsMdGenerator do
  subject(:generator) { described_class }

  let(:module_name) { "lib" }
  let(:tree_text) { "lib/\n  foo.rb\n  utils.rb\n" }
  let(:files) do
    [
      { name: "foo.rb", path: "/project/lib/foo.rb", classes: [{ name: "Foo", type: "class", has_doc?: true, line: 1 }], imports: [] },
      { name: "utils.rb", path: "/project/lib/utils.rb", classes: [{ name: "Utils", type: "module", has_doc?: false, line: 1 }], imports: [] }
    ]
  end

  describe ".generate" do
    it "works without config (backward compat)" do
      result = generator.generate(module_name, tree_text, files)
      expect(result).to include("# lib")
      expect(result).to include("developer to fill in")
    end

    it "works with config but no llm section (existing behavior preserved)" do
      config = AutoDoc::Config.load("/tmp")
      result = generator.generate(module_name, tree_text, files, config: config)
      expect(result).to include("developer to fill in")
    end

    it "includes public symbols from files" do
      result = generator.generate(module_name, tree_text, files)
      expect(result).to include("| Foo | class |")
      expect(result).to include("| Utils | module |")
    end

    it "includes the directory tree text" do
      result = generator.generate(module_name, tree_text, files)
      expect(result).to include("foo.rb")
      expect(result).to include("utils.rb")
    end

    it "includes generated timestamp" do
      result = generator.generate(module_name, tree_text, files)
      expect(result).to match(/Generated by auto-doc/)
      expect(result).to match(/\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}/)
    end

    context "with output_path" do
      let(:output_dir) { Dir.mktmpdir }
      let(:output_path) { File.join(output_dir, "AGENTS.md") }

      after { FileUtils.remove_entry(output_dir) }

      it "writes rendered content to disk" do
        generator.generate(module_name, tree_text, files, output_path: output_path)
        expect(File.exist?(output_path)).to be true
        content = File.read(output_path)
        expect(content).to include("# lib")
      end
    end
  end

  describe "LLM integration" do
    before do
      @original_disable_llm = ENV["AUTO_DOC_DISABLE_LLM"]
      ENV.delete("AUTO_DOC_DISABLE_LLM")
    end

    after do
      if @original_disable_llm
        ENV["AUTO_DOC_DISABLE_LLM"] = @original_disable_llm
      else
        ENV.delete("AUTO_DOC_DISABLE_LLM")
      end
    end

    let(:llm_project_dir) { Dir.mktmpdir }
    let(:llm_config) do
      File.write(File.join(llm_project_dir, ".autodoc.yml"), <<~YAML)
        llm:
          provider: openai
          endpoint: https://api.openai.com/v1
          api_key: sk-test
          model: gpt-4o
      YAML
      AutoDoc::Config.load(llm_project_dir)
    end
    after { FileUtils.remove_entry(llm_project_dir) }

    let(:http) { double("Net::HTTP") }
    let(:response) { double("Net::HTTPResponse") }

    before do
      allow(Net::HTTP).to receive(:new).and_return(http)
      allow(http).to receive(:open_timeout=)
      allow(http).to receive(:read_timeout=)
      allow(http).to receive(:use_ssl=)
    end

    it "uses LLM for purpose_summary when configured" do
      allow(http).to receive(:request).and_return(response)
      allow(response).to receive(:value).and_return(nil)
      allow(response).to receive(:body).and_return(
        '{"choices":[{"message":{"content":"The lib module contains core application classes."}}]}'
      )

      result = generator.generate(module_name, tree_text, files, config: llm_config)
      expect(result).to include("The lib module contains core application classes.")
      expect(result).not_to include("developer to fill in")
    end

    it "falls back to developer to fill in when LLM call fails" do
      allow(http).to receive(:request).and_raise(SocketError, "connection refused")

      result = generator.generate(module_name, tree_text, files, config: llm_config)
      expect(result).to include("developer to fill in")
    end

    it "rescues StandardError from LLM code and falls back to developer to fill in" do
      allow(http).to receive(:request).and_raise(StandardError, "Unexpected error")

      result = generator.generate(module_name, tree_text, files, config: llm_config)
      expect(result).to include("developer to fill in")
    end

    it "skips LLM entirely when AUTO_DOC_DISABLE_LLM is set" do
      original_enabled = ENV.delete("AUTO_DOC_DISABLE_LLM")
      ENV["AUTO_DOC_DISABLE_LLM"] = "true"

      allow(http).to receive(:request).and_return(response)
      allow(response).to receive(:value).and_return(nil)
      allow(response).to receive(:body).and_return(
        '{"choices":[{"message":{"content":"Should never be called."}}]}'
      )

      result = generator.generate(module_name, tree_text, files, config: llm_config)
      expect(result).to include("developer to fill in")
      expect(result).not_to include("Should never be called.")

    ensure
      if original_enabled
        ENV["AUTO_DOC_DISABLE_LLM"] = original_enabled
      else
        ENV.delete("AUTO_DOC_DISABLE_LLM")
      end
    end

    context "with LLM primary mode" do
      let(:primary_project_dir) { Dir.mktmpdir }
      let(:primary_config) do
        File.write(File.join(primary_project_dir, ".autodoc.yml"), <<~YAML)
          llm:
            provider: openai
            endpoint: https://api.openai.com/v1
            api_key: sk-test
            model: gpt-4o
            primary: true
        YAML
        AutoDoc::Config.load(primary_project_dir)
      end
      after { FileUtils.remove_entry(primary_project_dir) }

      before do
        allow(Net::HTTP).to receive(:new).and_return(http)
        allow(http).to receive(:open_timeout=)
        allow(http).to receive(:read_timeout=)
        allow(http).to receive(:use_ssl=)
      end

      it "uses LLM text when LLM succeeds" do
        allow(http).to receive(:request).and_return(response)
        allow(response).to receive(:value).and_return(nil)
        allow(response).to receive(:body).and_return(
          '{"choices":[{"message":{"content":"Primary mode LLM summary"}}]}'
        )

        result = generator.generate(module_name, tree_text, files, config: primary_config)
        expect(result).to include("Primary mode LLM summary")
        expect(result).not_to include("developer to fill in")
        expect(result).not_to include("static summary")
      end

      it "shows warning text when LLM fails" do
        allow(http).to receive(:request).and_raise(SocketError, "connection refused")

        expect {
          result = generator.generate(module_name, tree_text, files, config: primary_config)
          expect(result).to include("⚠ LLM unavailable — static summary")
          expect(result).not_to include("developer to fill in")
        }.to output(/LLM unavailable/).to_stderr
      end

      it "does not emit stderr warning when llm_primary? is false" do
        allow(http).to receive(:request).and_raise(SocketError, "connection refused")

        expect {
          result = generator.generate(module_name, tree_text, files, config: llm_config)
          expect(result).to include("developer to fill in")
        }.not_to output.to_stderr
      end
    end
  end

  describe "#generate" do
    it "works with instance as well" do
      instance = described_class.new(module_name, tree_text, files)
      result = instance.generate
      expect(result).to include("# lib")
    end
  end
end
