# frozen_string_literal: true

require "spec_helper"
require "tmpdir"

RSpec.describe AutoDoc::Generator::AgentsOverviewGenerator do
  subject(:generator) { described_class }

  let(:project_name) { "MyApp" }
  let(:module_roots) { ["/project/app"] }
  let(:tree_text) { "app/\n  models/\n    user.rb\n  controllers/\n    users_controller.rb\n" }
  let(:analyses) do
    {
      "/project/app/models/user.rb" => {
        definitions: [
          { name: "User", type: :class, has_doc?: true, methods: [{ name: "find" }] }
        ],
        imports: [{ target: "active_record", type: "require" }]
      },
      "/project/app/controllers/users_controller.rb" => {
        definitions: [
          { name: "UsersController", type: :class, has_doc?: false, methods: [{ name: "index" }, { name: "show" }] }
        ],
        imports: []
      }
    }
  end

  describe ".generate" do
    context "section rendering with config" do
      let(:config) do
        AutoDoc::Config.load("/tmp", llm: { primary: false, endpoint: nil, api_key: nil })
      end

      it "contains all expected sections" do
        result = generator.generate(project_name, analyses, module_roots, tree_text, config: config)
        expect(result).to include("# MyApp")
        expect(result).to include("## Project Overview")
        expect(result).to include("## Directory Structure")
        expect(result).to include("## Technology Stack")
        expect(result).to include("## Architecture")
        expect(result).to include("## Build & Test Commands")
        expect(result).to include("## Key Conventions")
        expect(result).to include("## External Dependencies")
      end

      it "renders directory tree text" do
        result = generator.generate(project_name, analyses, module_roots, tree_text, config: config)
        expect(result).to include("user.rb")
        expect(result).to include("users_controller.rb")
      end

      it "renders Build & Test Commands table" do
        result = generator.generate(project_name, analyses, module_roots, tree_text, config: config)
        expect(result).to include("| `bundle exec rspec` | Run the full test suite |")
      end

      it "renders External Dependencies table" do
        result = generator.generate(project_name, analyses, module_roots, tree_text, config: config)
        expect(result).to include("| active_record | require |")
      end

      it "includes generated timestamp" do
        result = generator.generate(project_name, analyses, module_roots, tree_text, config: config)
        expect(result).to match(/Generated by auto-doc/)
        expect(result).to match(/\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}/)
      end
    end

    context "without config (backward compat)" do
      it "returns rendered markdown with all sections present" do
        result = generator.generate(project_name, analyses, module_roots, tree_text)
        expect(result).to include("## Project Overview")
        expect(result).to include("## Directory Structure")
        expect(result).to include("## Technology Stack")
        expect(result).to include("## External Dependencies")
      end

      it "includes developer to fill in for LLM-generated sections" do
        result = generator.generate(project_name, analyses, module_roots, tree_text)
        expect(result).to include("developer to fill in")
      end

      it "works with nil config" do
        result = generator.generate(project_name, analyses, module_roots, tree_text, config: nil)
        expect(result).to include("developer to fill in")
      end
    end

    context "with output_path" do
      let(:output_dir) { Dir.mktmpdir }
      let(:output_path) { File.join(output_dir, "AGENTS.md") }
      let(:config) do
        AutoDoc::Config.load("/tmp", llm: { primary: false, endpoint: nil, api_key: nil })
      end

      after { FileUtils.remove_entry(output_dir) }

      it "writes rendered content to disk" do
        generator.generate(project_name, analyses, module_roots, tree_text, config: config, output_path: output_path)
        expect(File.exist?(output_path)).to be true
        content = File.read(output_path)
        expect(content).to include("# MyApp")
        expect(content).to include("## Project Overview")
      end
    end

    context "with empty analyses" do
      let(:empty_analyses) { {} }
      let(:config) do
        AutoDoc::Config.load("/tmp", llm: { primary: false, endpoint: nil, api_key: nil })
      end

      it "returns all sections present with fallback text" do
        result = generator.generate(project_name, empty_analyses, module_roots, tree_text, config: config)
        expect(result).to include("## Project Overview")
        expect(result).to include("## Directory Structure")
        expect(result).to include("## Technology Stack")
        expect(result).to include("## External Dependencies")
      end

      it "shows No external dependencies detected for empty analyses" do
        result = generator.generate(project_name, empty_analyses, module_roots, tree_text, config: config)
        expect(result).to include("No external dependencies detected")
      end
    end
  end

  describe "LLM integration" do
    let(:tmpdir) { Dir.mktmpdir }
    after { FileUtils.remove_entry(tmpdir) }

    let(:primary_llm_config) do
      AutoDoc::Config.load(tmpdir, llm: { endpoint: "https://test", api_key: "test", model: "gpt-4o", primary: true })
    end

    context "with LLM primary mode and successful responses" do
      it "uses LLM text for all four sections and does not show placeholders" do
        mock_llm_client({
          "overview describing" => "MyApp is a documentation tool for AI agent workflows.",
          "technology stack"    => "Ruby (Rails), PostgreSQL, Redis",
          "architecture of the" => "Layered architecture with service objects",
          "coding conventions"  => "RuboCop style, RSpec for testing"
        })

        result = generator.generate(project_name, analyses, module_roots, tree_text, config: primary_llm_config)
        expect(result).to include("MyApp is a documentation tool for AI agent workflows.")
        expect(result).to include("Ruby (Rails), PostgreSQL, Redis")
        expect(result).to include("Layered architecture with service objects")
        expect(result).to include("RuboCop style, RSpec for testing")
        expect(result).not_to include("developer to fill in")
        expect(result).not_to include("LLM unavailable")
      end
    end

    context "when LLM call fails in primary mode" do
      it "falls back to LLM unavailable warning for all sections" do
        client = instance_double(AutoDoc::LLM::Client)
        allow(client).to receive(:chat).and_raise(SocketError, "connection refused")
        allow(AutoDoc::LLM::Client).to receive(:build_if_configured).and_return(client)

        expect {
          result = generator.generate(project_name, analyses, module_roots, tree_text, config: primary_llm_config)
          expect(result).to include("⚠ LLM unavailable — project overview")
          expect(result).to include("⚠ LLM unavailable — architecture")
          expect(result).not_to include("developer to fill in")
        }.to output(/LLM unavailable/).to_stderr
      end
    end

    context "with llm_primary? false (non-primary mode)" do
      let(:non_primary_config) do
        AutoDoc::Config.load(tmpdir, llm: { endpoint: "https://test", api_key: "test", model: "gpt-4o", primary: false })
      end

      it "skips LLM entirely and shows developer to fill in" do
        client = instance_double(AutoDoc::LLM::Client)
        allow(client).to receive(:chat).and_raise(SocketError, "connection refused")
        allow(AutoDoc::LLM::Client).to receive(:build_if_configured).and_return(client)

        result = generator.generate(project_name, analyses, module_roots, tree_text, config: non_primary_config)
        expect(result).to include("developer to fill in")
        expect(result).not_to include("LLM unavailable")
      end

      it "does not emit stderr warning" do
        result = generator.generate(project_name, analyses, module_roots, tree_text, config: non_primary_config)
        expect(result).to include("developer to fill in")
      end
    end
  end

  describe "#generate" do
    it "works with instance as well" do
      instance = described_class.new(project_name, analyses, module_roots, tree_text)
      result = instance.generate
      expect(result).to include("# MyApp")
      expect(result).to include("developer to fill in")
    end
  end
end
