# frozen_string_literal: true

require "spec_helper"
require "tmpdir"

RSpec.describe AutoDoc::Generator::AgentsMdGenerator do
  subject(:generator) { described_class }

  let(:module_name) { "lib" }
  let(:tree_text) { "lib/\n  foo.rb\n  utils.rb\n" }
  let(:files) do
    [
      { name: "foo.rb", path: "/project/lib/foo.rb", classes: [{ name: "Foo", type: "class", has_doc?: true, line: 1 }], imports: [] },
      { name: "utils.rb", path: "/project/lib/utils.rb", classes: [{ name: "Utils", type: "module", has_doc?: false, line: 1 }], imports: [] }
    ]
  end

  describe ".generate" do
    it "works without config (backward compat)" do
      result = generator.generate(module_name, tree_text, files)
      expect(result).to include("# lib")
      expect(result).to include("developer to fill in")
    end

    it "works with config but no llm section (existing behavior preserved)" do
      config = AutoDoc::Config.load("/tmp")
      result = generator.generate(module_name, tree_text, files, config: config)
      expect(result).to include("developer to fill in")
    end

    it "includes public symbols from files" do
      result = generator.generate(module_name, tree_text, files)
      expect(result).to include("| Foo | class |")
      expect(result).to include("| Utils | module |")
    end

    it "includes the directory tree text" do
      result = generator.generate(module_name, tree_text, files)
      expect(result).to include("foo.rb")
      expect(result).to include("utils.rb")
    end

    it "includes generated timestamp" do
      result = generator.generate(module_name, tree_text, files)
      expect(result).to match(/Generated by auto-doc/)
      expect(result).to match(/\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}/)
    end

    context "with output_path" do
      let(:output_dir) { Dir.mktmpdir }
      let(:output_path) { File.join(output_dir, "AGENTS.md") }

      after { FileUtils.remove_entry(output_dir) }

      it "writes rendered content to disk" do
        generator.generate(module_name, tree_text, files, output_path: output_path)
        expect(File.exist?(output_path)).to be true
        content = File.read(output_path)
        expect(content).to include("# lib")
      end
    end
  end

  describe "LLM integration" do
    let(:tmpdir) { Dir.mktmpdir }
    after { FileUtils.remove_entry(tmpdir) }

    let(:llm_config) do
      AutoDoc::Config.load(tmpdir, llm: { endpoint: "https://test", api_key: "test", model: "gpt-4o" })
    end
    let(:no_llm_config) { AutoDoc::Config.load(tmpdir) }

    it "uses LLM for purpose_summary when configured with primary mode" do
      mock_llm_client({
        "summary of what this module does" => "The lib module contains core application classes."
      })

      primary_cfg = AutoDoc::Config.load(tmpdir, llm: {
        endpoint: "https://test", api_key: "test", model: "gpt-4o", primary: true
      })
      result = generator.generate(module_name, tree_text, files, config: primary_cfg)
      expect(result).to include("The lib module contains core application classes.")
      expect(result).not_to include("developer to fill in")
    end

    it "falls back to developer to fill in when LLM call fails" do
      client = instance_double(AutoDoc::LLM::Client)
      allow(client).to receive(:chat).and_raise(SocketError, "connection refused")
      allow(AutoDoc::LLM::Client).to receive(:build_if_configured).and_return(client)

      result = generator.generate(module_name, tree_text, files, config: llm_config)
      expect(result).to include("developer to fill in")
    end

    it "rescues StandardError from LLM code and falls back to developer to fill in" do
      client = instance_double(AutoDoc::LLM::Client)
      allow(client).to receive(:chat).and_raise(StandardError, "Unexpected error")
      allow(AutoDoc::LLM::Client).to receive(:build_if_configured).and_return(client)

      result = generator.generate(module_name, tree_text, files, config: llm_config)
      expect(result).to include("developer to fill in")
    end

    it "skips LLM entirely when AUTO_DOC_DISABLE_LLM is set" do
      ENV["AUTO_DOC_DISABLE_LLM"] = "true"

      result = generator.generate(module_name, tree_text, files, config: llm_config)
      expect(result).to include("developer to fill in")

      ENV.delete("AUTO_DOC_DISABLE_LLM")
    end

    context "with LLM primary mode" do
      let(:primary_config) do
        AutoDoc::Config.load(tmpdir, llm: {
          endpoint: "https://test", api_key: "test", model: "gpt-4o", primary: true
        })
      end

      it "uses LLM text when LLM succeeds" do
        mock_llm_client({
          "summary of what this module does" => "Primary mode LLM summary"
        })

        result = generator.generate(module_name, tree_text, files, config: primary_config)
        expect(result).to include("Primary mode LLM summary")
        expect(result).not_to include("developer to fill in")
        expect(result).not_to include("static summary")
      end

      it "shows warning text when LLM fails" do
        client = instance_double(AutoDoc::LLM::Client)
        allow(client).to receive(:chat).and_raise(SocketError, "connection refused")
        allow(AutoDoc::LLM::Client).to receive(:build_if_configured).and_return(client)

        expect {
          result = generator.generate(module_name, tree_text, files, config: primary_config)
          expect(result).to include("⚠ LLM unavailable — static summary")
          expect(result).not_to include("developer to fill in")
        }.to output(/LLM unavailable/).to_stderr
      end

      it "does not emit stderr warning when llm_primary? is false" do
        client = instance_double(AutoDoc::LLM::Client)
        allow(client).to receive(:chat).and_raise(SocketError, "connection refused")
        allow(AutoDoc::LLM::Client).to receive(:build_if_configured).and_return(client)

        expect {
          result = generator.generate(module_name, tree_text, files, config: llm_config)
          expect(result).to include("developer to fill in")
        }.not_to output.to_stderr
      end
    end
  end

  describe "#generate" do
    it "works with instance as well" do
      instance = described_class.new(module_name, tree_text, files)
      result = instance.generate
      expect(result).to include("# lib")
    end
  end
end
