# frozen_string_literal: true

require "spec_helper"
require "tmpdir"

RSpec.describe AutoDoc::Generator::C4DiagramGenerator do
  subject(:generator) { described_class }

  let(:title) { "MyApp" }

  describe ".generate_context" do
    let(:external_systems) do
      [
        { name: "Git", interaction: "reads repository" },
        { name: "Filesystem", interaction: "writes documentation" }
      ]
    end
    let(:internal_system) { { name: "MyApp" } }

    it "includes internal system node" do
      result = generator.generate_context(title, external_systems, internal_system)
      expect(result).to include("MyApp")
    end

    it "includes external system nodes" do
      result = generator.generate_context(title, external_systems, internal_system)
      expect(result).to include("Git")
      expect(result).to include("Filesystem")
    end

    it "includes interaction labels on edges" do
      result = generator.generate_context(title, external_systems, internal_system)
      expect(result).to include("reads repository")
      expect(result).to include("writes documentation")
    end

    it "includes the title" do
      result = generator.generate_context(title, external_systems, internal_system)
      expect(result).to include("MyApp")
    end

    context "with empty external systems" do
      let(:external_systems) { [] }

      it "returns valid skeleton with internal system" do
        result = generator.generate_context(title, external_systems, internal_system)
        expect(result).to include("graph TB")
        expect(result).to include("MyApp")
        expect(result).to include("Generated by auto-doc")
      end
    end

    context "with output_path provided" do
      let(:output_dir) { Dir.mktmpdir }
      let(:output_path) { File.join(output_dir, "c4_context.mmd") }

      after { FileUtils.remove_entry(output_dir) }

      it "writes the rendered content to file" do
        generator.generate_context(title, external_systems, internal_system, output_path: output_path)
        expect(File.exist?(output_path)).to be true
        content = File.read(output_path)
        expect(content).to include("graph TB")
      end
    end

    it "includes the generated timestamp" do
      result = generator.generate_context(title, external_systems, internal_system)
      expect(result).to match(/Generated by auto-doc/)
    end
  end

  describe ".generate_container" do
    let(:modules) do
      [
        { name: "Parser", description: "Parses source code" },
        { name: "Renderer", description: "Renders diagrams" }
      ]
    end
    let(:data_flows) do
      [
        { from: "Parser", to: "Renderer", label: "AST data" }
      ]
    end

    it "includes module nodes with descriptions" do
      result = generator.generate_container(title, modules, data_flows)
      expect(result).to include("Parser")
      expect(result).to include("Parses source code")
      expect(result).to include("Renderer")
      expect(result).to include("Renders diagrams")
    end

    it "includes data flow edges" do
      result = generator.generate_container(title, modules, data_flows)
      expect(result).to include("Parser")
      expect(result).to include("Renderer")
      expect(result).to include("AST data")
    end

    context "with empty modules" do
      let(:modules) { [] }
      let(:data_flows) { [] }

      it "returns valid skeleton" do
        result = generator.generate_container(title, modules, data_flows)
        expect(result).to include("graph TB")
        expect(result).to include("Generated by auto-doc")
      end
    end

    context "with output_path provided" do
      let(:output_dir) { Dir.mktmpdir }
      let(:output_path) { File.join(output_dir, "c4_container.mmd") }

      after { FileUtils.remove_entry(output_dir) }

      it "writes the rendered content to file" do
        generator.generate_container(title, modules, data_flows, output_path: output_path)
        expect(File.exist?(output_path)).to be true
        content = File.read(output_path)
        expect(content).to include("graph TB")
      end
    end

    it "includes the generated timestamp" do
      result = generator.generate_container(title, modules, data_flows)
      expect(result).to match(/Generated by auto-doc/)
    end
  end

  describe "#generate (instance method)" do
    it "works with instance directly for context" do
      instance = described_class.new(:context, title, external_systems: [], internal_system: { name: title })
      result = instance.generate
      expect(result).to include("graph TB")
    end

    it "works with instance directly for container" do
      instance = described_class.new(:container, title, modules: [], data_flows: [])
      result = instance.generate
      expect(result).to include("graph TB")
    end
  end
end
