# frozen_string_literal: true

require "spec_helper"
require "tmpdir"

RSpec.describe AutoDoc::Generator::ClassDiagramGenerator do
  subject(:generator) { described_class }

  let(:title) { "MyProject" }

  describe ".generate" do
    let(:class_hierarchy) do
      [
        { name: "User", parent: "ApplicationRecord", includes: ["Authenticatable"], extends: [], methods: ["find_active"] },
        { name: "Admin", parent: "User", includes: [], extends: ["Role"], methods: [] }
      ]
    end

    it "starts with classDiagram directive" do
      result = generator.generate(title, class_hierarchy)
      expect(result).to include("classDiagram")
    end

    it "includes class nodes" do
      result = generator.generate(title, class_hierarchy)
      expect(result).to include("class User")
      expect(result).to include("class Admin")
    end

    it "includes inheritance arrows (<|--)" do
      result = generator.generate(title, class_hierarchy)
      expect(result).to include("ApplicationRecord <|-- User")
      expect(result).to include("User <|-- Admin")
    end

    it "includes method definitions" do
      result = generator.generate(title, class_hierarchy)
      expect(result).to include("find_active")
    end

    it "includes the title" do
      result = generator.generate(title, class_hierarchy)
      expect(result).to include("MyProject")
    end

    context "with includes" do
      let(:class_hierarchy) do
        [
          { name: "User", parent: nil, includes: ["Authenticatable"], extends: [], methods: [] }
        ]
      end

      it "includes dashed include arrows (<|..)" do
        result = generator.generate(title, class_hierarchy)
        expect(result).to include("Authenticatable <|.. User")
      end
    end

    context "with extends" do
      let(:class_hierarchy) do
        [
          { name: "Admin", parent: nil, includes: [], extends: ["Role"], methods: [] }
        ]
      end

      it "includes extends arrows (--|>)" do
        result = generator.generate(title, class_hierarchy)
        expect(result).to include("Admin --|> Role")
      end
    end

    context "with empty hierarchy" do
      let(:class_hierarchy) { [] }

      it "returns valid empty classDiagram" do
        result = generator.generate(title, class_hierarchy)
        expect(result).to include("classDiagram")
        expect(result).to include("Generated by auto-doc")
        expect(result).to include("MyProject")
      end
    end

    context "with output_path provided" do
      let(:output_dir) { Dir.mktmpdir }
      let(:output_path) { File.join(output_dir, "class_diagram.mmd") }

      after { FileUtils.remove_entry(output_dir) }

      it "writes the rendered content to file" do
        generator.generate(title, class_hierarchy, output_path: output_path)
        expect(File.exist?(output_path)).to be true
        content = File.read(output_path)
        expect(content).to include("classDiagram")
      end
    end

    it "includes the generated timestamp" do
      result = generator.generate(title, class_hierarchy)
      expect(result).to match(/Generated by auto-doc/)
    end
  end

  describe "#generate" do
    it "works with instance as well" do
      instance = described_class.new(title, [])
      result = instance.generate
      expect(result).to include("classDiagram")
    end
  end
end
