# frozen_string_literal: true

require "spec_helper"
require "tmpdir"

RSpec.describe AutoDoc::Generator::DiagramGenerator do
  subject(:generator) { described_class }

  let(:title) { "MyProject" }
  let(:graph_nodes) { %w[User MathUtils] }
  let(:graph_edges) do
    [
      { from: "user.rb", to: "math_utils.rb", type: "require" }
    ]
  end

  describe ".generate" do
    it "starts with graph TB mermaid directive" do
      result = generator.generate(title, graph_nodes, graph_edges)
      expect(result).to include("graph TB")
    end

    it "includes all node declarations" do
      result = generator.generate(title, graph_nodes, graph_edges)
      expect(result).to include("User")
      expect(result).to include("MathUtils")
    end

    it "includes edge declarations with arrow syntax" do
      result = generator.generate(title, graph_nodes, graph_edges)
      expect(result).to match(/-->/)
    end

    it "includes the title as comment" do
      result = generator.generate(title, graph_nodes, graph_edges)
      expect(result).to include("MyProject")
    end

    context "with empty graph data" do
      let(:graph_nodes) { [] }
      let(:graph_edges) { [] }

      it "returns valid skeleton" do
        result = generator.generate(title, graph_nodes, graph_edges)
        expect(result).to include("graph TB")
        expect(result).to include("Generated by auto-doc")
      end
    end

    context "with output_path provided" do
      let(:output_dir) { Dir.mktmpdir }
      let(:output_path) { File.join(output_dir, "deps.mmd") }

      after { FileUtils.remove_entry(output_dir) }

      it "writes the rendered content to file" do
        generator.generate(title, graph_nodes, graph_edges, output_path: output_path)
        expect(File.exist?(output_path)).to be true
        content = File.read(output_path)
        expect(content).to include("graph TB")
      end
    end

    it "includes the generated timestamp" do
      result = generator.generate(title, graph_nodes, graph_edges)
      expect(result).to match(/Generated by auto-doc/)
    end
  end

  describe "#generate" do
    it "works with instance as well" do
      instance = described_class.new(title, graph_nodes, graph_edges)
      result = instance.generate
      expect(result).to include("graph TB")
    end
  end
end
