# frozen_string_literal: true

require "spec_helper"
require "tmpdir"

RSpec.describe AutoDoc::Generator::ERDGenerator do
  subject(:generator) { described_class }

  let(:title) { "MyApp" }

  describe ".generate" do
    let(:tables) do
      [
        {
          name: "users",
          columns: [
            { name: "id", type: "integer", pk: true, fk: false, null: false },
            { name: "name", type: "string", pk: false, fk: false, null: false },
            { name: "email", type: "string", pk: false, fk: false, null: true }
          ]
        },
        {
          name: "posts",
          columns: [
            { name: "id", type: "integer", pk: true, fk: false, null: false },
            { name: "title", type: "string", pk: false, fk: false, null: false },
            { name: "user_id", type: "integer", pk: false, fk: true, null: false }
          ]
        }
      ]
    end

    let(:relationships) do
      [
        { from: "users", to: "posts", cardinality_from: "||", cardinality_to: "o{", label: "has_many" }
      ]
    end

    it "starts with erDiagram directive" do
      result = generator.generate(title, tables, relationships)
      expect(result).to include("erDiagram")
    end

    it "includes table definitions with typed columns" do
      result = generator.generate(title, tables, relationships)
      expect(result).to include("users {")
      expect(result).to include("posts {")
      expect(result).to include("integer id")
      expect(result).to include("string name")
      expect(result).to include("string email")
    end

    it "marks primary key columns" do
      result = generator.generate(title, tables, relationships)
      expect(result).to include("integer id PK")
    end

    it "marks foreign key columns" do
      result = generator.generate(title, tables, relationships)
      expect(result).to include("integer user_id FK")
    end

    it "marks NOT NULL columns" do
      result = generator.generate(title, tables, relationships)
      expect(result).to include("NOT NULL")
    end

    it "includes relationship lines with -- syntax" do
      result = generator.generate(title, tables, relationships)
      expect(result).to match(/--/)
    end

    it "includes cardinality markers in relationship lines" do
      result = generator.generate(title, tables, relationships)
      expect(result).to include("||")
      expect(result).to include("o{")
    end

    it "includes the title" do
      result = generator.generate(title, tables, relationships)
      expect(result).to include("MyApp")
    end

    context "with empty tables" do
      let(:tables) { [] }
      let(:relationships) { [] }

      it "returns valid erDiagram skeleton" do
        result = generator.generate(title, tables, relationships)
        expect(result).to include("erDiagram")
        expect(result).to include("Generated by auto-doc")
      end
    end

    context "with empty relationships" do
      let(:relationships) { [] }

      it "renders tables only with no relationship lines" do
        result = generator.generate(title, tables, relationships)
        expect(result).to include("users {")
        expect(result).to include("posts {")
        expect(result).not_to match(/^\s+--/)
      end
    end

    context "with output_path provided" do
      let(:output_dir) { Dir.mktmpdir }
      let(:output_path) { File.join(output_dir, "erd.mmd") }

      after { FileUtils.remove_entry(output_dir) }

      it "writes the rendered content to file" do
        generator.generate(title, tables, relationships, output_path: output_path)
        expect(File.exist?(output_path)).to be true
        content = File.read(output_path)
        expect(content).to include("erDiagram")
      end
    end

    it "includes the generated timestamp" do
      result = generator.generate(title, tables, relationships)
      expect(result).to match(/Generated by auto-doc/)
    end
  end

  describe "#generate" do
    it "works with instance as well" do
      instance = described_class.new(title, [], [])
      result = instance.generate
      expect(result).to include("erDiagram")
    end
  end
end
