# frozen_string_literal: true

require "spec_helper"
require "tmpdir"

RSpec.describe AutoDoc::Generator::IndexGenerator do
  subject(:generator) { described_class }

  let(:dir_name) { "lib" }
  let(:config) { AutoDoc::Config.load("/tmp") }
  let(:analyses) do
    {
      "/project/lib/foo.rb" => {
        definitions: [
          { name: "Foo", type: :class, line: 1, has_doc?: true, methods: [{ name: "bar", line: 5 }] },
          { name: "Foo#bar", type: :method, line: 5, has_doc?: false }
        ],
        imports: [
          { path: "json", type: :require }
        ],
        docs: [
          { target_name: "Foo", target_type: :class, has_summary?: true }
        ]
      },
      "/project/lib/utils.rb" => {
        definitions: [
          { name: "Utils", type: :module, line: 1, has_doc?: false, methods: [] }
        ],
        imports: [
          { path: "fileutils", type: :require }
        ],
        docs: []
      }
    }
  end

  describe ".generate" do
    it "returns rendered markdown with the directory name" do
      result = generator.generate(dir_name, analyses, config)
      expect(result).to include("INDEX: lib")
    end

    it "includes a files table with required columns" do
      result = generator.generate(dir_name, analyses, config)
      expect(result).to include("| # | File | Classes | Modules | Methods | Documented |")
    end

    it "includes each file in the files table" do
      result = generator.generate(dir_name, analyses, config)
      expect(result).to include("foo.rb")
      expect(result).to include("utils.rb")
    end

    it "includes a symbols table" do
      result = generator.generate(dir_name, analyses, config)
      expect(result).to include("| Symbol | Type | File | Line | Documented |")
    end

    it "includes symbols sorted alphabetically" do
      result = generator.generate(dir_name, analyses, config)
      foo_pos = result.index("Foo")
      utils_pos = result.index("Utils")
      expect(foo_pos).to be < utils_pos
    end

    it "includes symbols with documented status" do
      result = generator.generate(dir_name, analyses, config)
      expect(result).to include("✅")
    end

    it "includes a dependencies table" do
      result = generator.generate(dir_name, analyses, config)
      expect(result).to include("| From | Type | To |")
      expect(result).to include("json")
      expect(result).to include("fileutils")
    end

    it "includes the generated timestamp" do
      result = generator.generate(dir_name, analyses, config)
      expect(result).to match(/Generated by auto-doc/)
      expect(result).to match(/\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}/)
    end

    context "when output_path is provided" do
      let(:output_dir) { Dir.mktmpdir }
      let(:output_path) { File.join(output_dir, "INDEX.md") }

      after { FileUtils.remove_entry(output_dir) }

      it "writes the rendered content to the file" do
        generator.generate(dir_name, analyses, config, output_path: output_path)
        expect(File.exist?(output_path)).to be true
        content = File.read(output_path)
        expect(content).to include("INDEX: lib")
      end
    end

    context "with empty analyses (no Ruby files)" do
      let(:analyses) { {} }

      it "renders without crashing" do
        result = generator.generate(dir_name, analyses, config)
        expect(result).to include("INDEX: lib")
        expect(result).to include("No Ruby files found")
        expect(result).to include("No symbols found")
        expect(result).to include("No dependencies detected")
      end
    end
  end

  describe "#generate" do
    it "works with instance as well" do
      instance = described_class.new(dir_name, analyses, config)
      result = instance.generate
      expect(result).to include("INDEX: lib")
    end
  end
end
