# frozen_string_literal: true

require "spec_helper"
require "tmpdir"

RSpec.describe AutoDoc::Generator::ReadmeGenerator do
  subject(:generator) { described_class }

  let(:project_name) { "MyProject" }
  let(:structure) do
    {
      "lib" => "lib/\n  math_utils.rb\n",
      "app" => "app/\n  user.rb\n"
    }
  end
  let(:summary_stats) do
    {
      total_modules: 2,
      total_classes: 5,
      total_methods: 10,
      coverage_pct: "80.0"
    }
  end

  describe ".generate" do
    it "returns rendered markdown with the project name" do
      result = generator.generate(project_name, structure, summary_stats)
      expect(result).to include("# MyProject")
    end

    it "includes the default overview text" do
      result = generator.generate(project_name, structure, summary_stats)
      expect(result).to include("Developer to fill in")
    end

    it "lists each directory in the files table" do
      result = generator.generate(project_name, structure, summary_stats)
      expect(result).to include("| lib | - | - | ❌ |")
      expect(result).to include("| app | - | - | ❌ |")
    end

    it "includes summary statistics" do
      result = generator.generate(project_name, structure, summary_stats)
      expect(result).to include("Total modules: 2")
      expect(result).to include("Total classes: 5")
      expect(result).to include("Total methods: 10")
      expect(result).to include("Documentation coverage: 80.0%")
    end

    it "includes the generated timestamp" do
      result = generator.generate(project_name, structure, summary_stats)
      expect(result).to match(/Generated by auto-doc/)
      expect(result).to match(/\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}/)
    end

    context "when output_path is provided" do
      let(:output_dir) { Dir.mktmpdir }
      let(:output_path) { File.join(output_dir, "README.md") }

      after { FileUtils.remove_entry(output_dir) }

      it "writes the rendered content to the file" do
        generator.generate(project_name, structure, summary_stats, output_path: output_path)
        expect(File.exist?(output_path)).to be true
        content = File.read(output_path)
        expect(content).to include("# MyProject")
      end
    end

    context "with empty structure" do
      let(:structure) { {} }

      it "renders without files table rows" do
        result = generator.generate(project_name, structure, summary_stats)
        expect(result).to include("| File | Classes/Modules | Methods | Documented? |")
        # No data rows between the header and the summary
        expect(result).to include("|------|-----------------|---------|-------------|")
        expect(result).to include("## Summary")
      end
    end

    context "with minimal summary stats" do
      let(:summary_stats) { {} }

      it "handles missing stats gracefully" do
        result = generator.generate(project_name, structure, summary_stats)
        expect(result).to include("N/A")
      end
    end
  end

  describe "#generate" do
    it "works with instance as well" do
      instance = described_class.new(project_name, structure, summary_stats)
      result = instance.generate
      expect(result).to include("# MyProject")
    end
  end

  describe "LLM integration" do
    let(:tmpdir) { Dir.mktmpdir }
    let(:analyses) { { "lib/foo.rb" => { definitions: [{ name: "Foo", type: :class }] } } }
    let(:mock_client) { instance_double(AutoDoc::LLM::Client) }
    let(:llm_config) do
      AutoDoc::Config.load(tmpdir, llm: { endpoint: "https://test", api_key: "test", model: "gpt-4o" })
    end
    let(:primary_config) do
      AutoDoc::Config.load(tmpdir, llm: {
        endpoint: "https://test", api_key: "test", model: "gpt-4o", primary: true
      })
    end
    after { FileUtils.remove_entry(tmpdir) }

    context "when llm_primary? is true" do
      before do
        allow(AutoDoc::LLM::Client).to receive(:build_if_configured).and_return(mock_client)
      end

      it "uses LLM-generated overview when LLM succeeds" do
        allow(AutoDoc::LLM::Summarizer).to receive(:summarize_module)
          .with(project_name, analyses, mock_client)
          .and_return("LLM-powered project overview")

        result = described_class.generate(project_name, structure, summary_stats,
          config: primary_config, analyses: analyses)
        expect(result).to include("LLM-powered project overview")
        expect(result).not_to include("Developer to fill in")
      end

      it "falls back to default overview when LLM call fails" do
        allow(AutoDoc::LLM::Summarizer).to receive(:summarize_module).and_raise(StandardError, "LLM error")

        expect {
          result = described_class.generate(project_name, structure, summary_stats,
            config: primary_config, analyses: analyses)
          expect(result).to include("Developer to fill in")
        }.to output(/LLM unavailable/).to_stderr
      end
    end

    context "when llm_primary? is false with LLM configured" do
      it "does not emit stderr warning when llm_primary? is false" do
        config_no_primary = instance_double(AutoDoc::Config,
          llm_primary?: false,
          llm_config: { endpoint: "https://test", api_key: "test", model: "test-model" })

        allow(AutoDoc::LLM::Client).to receive(:build_if_configured).and_return(mock_client)
        allow(AutoDoc::LLM::Summarizer).to receive(:summarize_module).and_return(nil)

        expect {
          result = described_class.generate(project_name, structure, summary_stats,
            config: config_no_primary, analyses: analyses)
          expect(result).to include("Developer to fill in")
        }.not_to output.to_stderr
      end
    end

    context "when llm_primary? is false" do
      it "uses default overview even when config has LLM section" do
        result = described_class.generate(project_name, structure, summary_stats,
          config: llm_config, analyses: analyses)
        expect(result).to include("Developer to fill in")
      end
    end

    context "when config is not provided" do
      it "uses default overview" do
        result = described_class.generate(project_name, structure, summary_stats)
        expect(result).to include("Developer to fill in")
      end
    end

    context "when analyses is nil" do
      it "uses default overview" do
        result = described_class.generate(project_name, structure, summary_stats,
          config: llm_config, analyses: nil)
        expect(result).to include("Developer to fill in")
      end
    end

    context "when analyses is empty" do
      it "uses default overview" do
        result = described_class.generate(project_name, structure, summary_stats,
          config: llm_config, analyses: {})
        expect(result).to include("Developer to fill in")
      end
    end
  end
end
