# frozen_string_literal: true

require "spec_helper"
require "tmpdir"

RSpec.describe AutoDoc::Generator::SummaryGenerator do
  subject(:generator) { described_class }

  let(:dir_name) { "lib" }
  let(:config) { AutoDoc::Config.load("/tmp") }
  let(:analyses) do
    {
      "/project/lib/foo.rb" => {
        definitions: [
          { name: "Foo", type: :class, line: 1, has_doc?: true, methods: [{ name: "bar", line: 5 }] }
        ],
        imports: [
          { path: "json", type: :require }
        ],
        docs: [
          { target_name: "Foo", target_type: :class, has_summary?: true, summary: "Main application class" }
        ]
      },
      "/project/lib/utils.rb" => {
        definitions: [
          { name: "Utils", type: :module, line: 1, has_doc?: false, methods: [] }
        ],
        imports: [
          { path: "fileutils", type: :require }
        ],
        docs: []
      }
    }
  end

  describe ".generate" do
    it "returns rendered markdown with purpose text inferred from dir name" do
      result = generator.generate(dir_name, analyses, config)
      expect(result).to include("SUMMARY: lib")
      expect(result).to include("Core library code")
    end

    it "includes key components section" do
      result = generator.generate(dir_name, analyses, config)
      expect(result).to include("| Component | Type | Summary |")
      expect(result).to include("Foo")
      expect(result).to include("Utils")
    end

    it "includes architecture pattern" do
      result = generator.generate(dir_name, analyses, config)
      expect(result).to match(/Architecture Pattern/)
      expect(result).to match(/Modular/)
    end

    it "includes dependencies overview" do
      result = generator.generate(dir_name, analyses, config)
      expect(result).to include("json")
      expect(result).to include("fileutils")
    end

    it "includes links to related documents" do
      result = generator.generate(dir_name, analyses, config)
      expect(result).to include("[INDEX.md](INDEX.md)")
      expect(result).to include("[AGENTS.md](AGENTS.md)")
    end

    it "includes the generated timestamp" do
      result = generator.generate(dir_name, analyses, config)
      expect(result).to match(/Generated by auto-doc/)
      expect(result).to match(/\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}/)
    end

    context "with empty analyses" do
      let(:analyses) { {} }

      it "handles gracefully" do
        result = generator.generate(dir_name, analyses, config)
        expect(result).to include("SUMMARY: lib")
        expect(result).to include("Core library code")
        expect(result).to include("_No key components identified._")
      end
    end

    context "with custom directory name not in hardcoded list" do
      let(:dir_name) { "services" }

      it "infers purpose from directory name" do
        result = generator.generate(dir_name, analyses, config)
        expect(result).to include("SUMMARY: services")
        expect(result).to include("Services")
      end
    end

    context "with output_path provided" do
      let(:output_dir) { Dir.mktmpdir }
      let(:output_path) { File.join(output_dir, "SUMMARY.md") }

      after { FileUtils.remove_entry(output_dir) }

      it "writes the rendered content to the file" do
        generator.generate(dir_name, analyses, config, output_path: output_path)
        expect(File.exist?(output_path)).to be true
        content = File.read(output_path)
        expect(content).to include("SUMMARY: lib")
      end
    end
  end

  describe "#generate" do
    it "works with instance as well" do
      instance = described_class.new(dir_name, analyses, config)
      result = instance.generate
      expect(result).to include("SUMMARY: lib")
    end
  end

  describe "LLM integration" do
    let(:tmpdir) { Dir.mktmpdir }
    after { FileUtils.remove_entry(tmpdir) }

    let(:llm_config) do
      AutoDoc::Config.load(tmpdir, llm: { endpoint: "https://test", api_key: "test", model: "gpt-4o" })
    end
    let(:no_llm_config) { AutoDoc::Config.load(tmpdir) }

    it "uses LLM when client is configured" do
      mock_llm_client({
        "what this module does" => "LLM-powered purpose: core library",
        "overall architecture" => "LLM-powered architecture: modular composition",
        "component relationships" => "- Foo (class): Main application class\n- Utils (module): Utility functions"
      })

      result = described_class.generate(dir_name, analyses, llm_config)
      expect(result).to include("LLM-powered purpose: core library")
      expect(result).to include("LLM-powered architecture: modular composition")
    end

    it "falls back to static when client not configured" do
      result = described_class.generate(dir_name, analyses, no_llm_config)
      expect(result).to include("Core library code")
      expect(result).to include("Modular library")
    end

    it "falls back to static when LLM call fails" do
      client = instance_double(AutoDoc::LLM::Client)
      allow(client).to receive(:chat).and_raise(SocketError, "connection refused")
      allow(AutoDoc::LLM::Client).to receive(:build_if_configured).and_return(client)

      result = described_class.generate(dir_name, analyses, llm_config)
      expect(result).to include("Core library code")
      expect(result).to include("Modular library")
      expect(result).to include("Foo")
      expect(result).to include("Utils")
    end

    it "rescues StandardError from LLM code and falls back to static values" do
      client = instance_double(AutoDoc::LLM::Client)
      allow(client).to receive(:chat).and_raise(StandardError, "Unexpected LLM error")
      allow(AutoDoc::LLM::Client).to receive(:build_if_configured).and_return(client)

      result = described_class.generate(dir_name, analyses, llm_config)
      expect(result).to include("Core library code")
      expect(result).to include("Modular library")
      expect(result).to include("Foo")
      expect(result).to include("Utils")
    end

    context "with LLM primary mode" do
      let(:primary_config) do
        AutoDoc::Config.load(tmpdir, llm: {
          endpoint: "https://test", api_key: "test", model: "gpt-4o", primary: true
        })
      end

      it "uses LLM text when LLM succeeds" do
        mock_llm_client({
          "what this module does" => "LLM primary purpose",
          "overall architecture" => "LLM primary architecture",
          "component relationships" => "LLM primary components"
        })

        result = described_class.generate(dir_name, analyses, primary_config)
        expect(result).to include("LLM primary purpose")
        expect(result).to include("LLM primary architecture")
        expect(result).to include("LLM primary components")
      end

      it "emits stderr warning and falls back to static when LLM fails" do
        client = instance_double(AutoDoc::LLM::Client)
        allow(client).to receive(:chat).and_raise(SocketError, "connection refused")
        allow(AutoDoc::LLM::Client).to receive(:build_if_configured).and_return(client)

        result = nil
        expect { result = described_class.generate(dir_name, analyses, primary_config) }
          .to output(/LLM unavailable for lib/).to_stderr
        expect(result).to include("Core library code")
        expect(result).to include("Modular library")
      end

      it "does not emit stderr warning when llm_primary? is false" do
        client = instance_double(AutoDoc::LLM::Client)
        allow(client).to receive(:chat).and_raise(SocketError, "connection refused")
        allow(AutoDoc::LLM::Client).to receive(:build_if_configured).and_return(client)

        expect { described_class.generate(dir_name, analyses, llm_config) }
          .not_to output(/LLM unavailable/).to_stderr
      end
    end
  end
end
