# frozen_string_literal: true

require "spec_helper"
require "tmpdir"

RSpec.describe AutoDoc::Generator::SummaryGenerator do
  subject(:generator) { described_class }

  let(:dir_name) { "lib" }
  let(:config) { AutoDoc::Config.load("/tmp") }
  let(:analyses) do
    {
      "/project/lib/foo.rb" => {
        definitions: [
          { name: "Foo", type: :class, line: 1, has_doc?: true, methods: [{ name: "bar", line: 5 }] }
        ],
        imports: [
          { path: "json", type: :require }
        ],
        docs: [
          { target_name: "Foo", target_type: :class, has_summary?: true, summary: "Main application class" }
        ]
      },
      "/project/lib/utils.rb" => {
        definitions: [
          { name: "Utils", type: :module, line: 1, has_doc?: false, methods: [] }
        ],
        imports: [
          { path: "fileutils", type: :require }
        ],
        docs: []
      }
    }
  end

  describe ".generate" do
    it "returns rendered markdown with purpose text inferred from dir name" do
      result = generator.generate(dir_name, analyses, config)
      expect(result).to include("SUMMARY: lib")
      expect(result).to include("Core library code")
    end

    it "includes key components section" do
      result = generator.generate(dir_name, analyses, config)
      expect(result).to include("| Component | Type | Summary |")
      expect(result).to include("Foo")
      expect(result).to include("Utils")
    end

    it "includes architecture pattern" do
      result = generator.generate(dir_name, analyses, config)
      expect(result).to match(/Architecture Pattern/)
      expect(result).to match(/Modular/)
    end

    it "includes dependencies overview" do
      result = generator.generate(dir_name, analyses, config)
      expect(result).to include("json")
      expect(result).to include("fileutils")
    end

    it "includes links to related documents" do
      result = generator.generate(dir_name, analyses, config)
      expect(result).to include("[INDEX.md](INDEX.md)")
      expect(result).to include("[AGENTS.md](AGENTS.md)")
    end

    it "includes the generated timestamp" do
      result = generator.generate(dir_name, analyses, config)
      expect(result).to match(/Generated by auto-doc/)
      expect(result).to match(/\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}/)
    end

    context "with empty analyses" do
      let(:analyses) { {} }

      it "handles gracefully" do
        result = generator.generate(dir_name, analyses, config)
        expect(result).to include("SUMMARY: lib")
        expect(result).to include("Core library code")
        expect(result).to include("_No key components identified._")
      end
    end

    context "with custom directory name not in hardcoded list" do
      let(:dir_name) { "services" }

      it "infers purpose from directory name" do
        result = generator.generate(dir_name, analyses, config)
        expect(result).to include("SUMMARY: services")
        expect(result).to include("Services")
      end
    end

    context "with output_path provided" do
      let(:output_dir) { Dir.mktmpdir }
      let(:output_path) { File.join(output_dir, "SUMMARY.md") }

      after { FileUtils.remove_entry(output_dir) }

      it "writes the rendered content to the file" do
        generator.generate(dir_name, analyses, config, output_path: output_path)
        expect(File.exist?(output_path)).to be true
        content = File.read(output_path)
        expect(content).to include("SUMMARY: lib")
      end
    end
  end

  describe "#generate" do
    it "works with instance as well" do
      instance = described_class.new(dir_name, analyses, config)
      result = instance.generate
      expect(result).to include("SUMMARY: lib")
    end
  end

  describe "LLM integration" do
    before do
      @original_disable_llm = ENV["AUTO_DOC_DISABLE_LLM"]
      ENV.delete("AUTO_DOC_DISABLE_LLM")
    end

    after do
      if @original_disable_llm
        ENV["AUTO_DOC_DISABLE_LLM"] = @original_disable_llm
      else
        ENV.delete("AUTO_DOC_DISABLE_LLM")
      end
    end

    let(:llm_project_dir) { Dir.mktmpdir }
    let(:llm_config) do
      File.write(File.join(llm_project_dir, ".autodoc.yml"), <<~YAML)
        llm:
          provider: openai
          endpoint: https://api.openai.com/v1
          api_key: sk-test
          model: gpt-4o
      YAML
      AutoDoc::Config.load(llm_project_dir)
    end
    let(:no_llm_project_dir) { Dir.mktmpdir }
    let(:no_llm_config) { AutoDoc::Config.load(no_llm_project_dir, { llm: { endpoint: nil, api_key: nil } }) }
    after do
      FileUtils.remove_entry(llm_project_dir)
      FileUtils.remove_entry(no_llm_project_dir)
    end

    let(:http) { double("Net::HTTP") }
    let(:response) { double("Net::HTTPResponse") }

    before do
      allow(Net::HTTP).to receive(:new).and_return(http)
      allow(http).to receive(:open_timeout=)
      allow(http).to receive(:read_timeout=)
      allow(http).to receive(:use_ssl=)
    end

    it "uses LLM when client is configured" do
      allow(http).to receive(:request).and_return(response).exactly(3).times
      allow(response).to receive(:value).and_return(nil).exactly(3).times
      allow(response).to receive(:body).and_return(
        '{"choices":[{"message":{"content":"LLM-powered purpose: core library"}}]}',
        '{"choices":[{"message":{"content":"LLM-powered architecture: modular composition"}}]}',
        '{"choices":[{"message":{"content":"- Foo (class): Main application class\n- Utils (module): Utility functions"}}]}'
      )

      result = described_class.generate(dir_name, analyses, llm_config)
      expect(result).to include("LLM-powered purpose: core library")
      expect(result).to include("LLM-powered architecture: modular composition")
    end

    it "falls back to static when client not configured" do
      # no_llm_config has no llm section, so Client.configured? returns false
      result = described_class.generate(dir_name, analyses, no_llm_config)
      expect(result).to include("Core library code")
      expect(result).to include("Modular library")
    end

    it "falls back to static when LLM call fails" do
      allow(http).to receive(:request).and_raise(SocketError, "connection refused")

      result = described_class.generate(dir_name, analyses, llm_config)
      expect(result).to include("Core library code")
      expect(result).to include("Modular library")
      expect(result).to include("Foo")
      expect(result).to include("Utils")
    end

    it "rescues StandardError from LLM code and falls back to static values" do
      # Make Client.new raise to trigger rescue inside private llm_xxx methods
      allow(AutoDoc::LLM::Client).to receive(:new).and_raise(StandardError, "Unexpected LLM error")

      result = described_class.generate(dir_name, analyses, llm_config)
      expect(result).to include("Core library code")
      expect(result).to include("Modular library")
      expect(result).to include("Foo")
      expect(result).to include("Utils")
    end

    context "with LLM primary mode" do
      let(:primary_project_dir) { Dir.mktmpdir }
      let(:primary_config) do
        File.write(File.join(primary_project_dir, ".autodoc.yml"), <<~YAML)
          llm:
            provider: openai
            endpoint: https://api.openai.com/v1
            api_key: sk-test
            model: gpt-4o
            primary: true
        YAML
        AutoDoc::Config.load(primary_project_dir)
      end
      after { FileUtils.remove_entry(primary_project_dir) }

      before do
        allow(Net::HTTP).to receive(:new).and_return(http)
        allow(http).to receive(:open_timeout=)
        allow(http).to receive(:read_timeout=)
        allow(http).to receive(:use_ssl=)
      end

      it "uses LLM text when LLM succeeds" do
        allow(http).to receive(:request).and_return(response).exactly(3).times
        allow(response).to receive(:value).and_return(nil).exactly(3).times
        allow(response).to receive(:body).and_return(
          '{"choices":[{"message":{"content":"LLM primary purpose"}}]}',
          '{"choices":[{"message":{"content":"LLM primary architecture"}}]}',
          '{"choices":[{"message":{"content":"LLM primary components"}}]}'
        )

        result = described_class.generate(dir_name, analyses, primary_config)
        expect(result).to include("LLM primary purpose")
        expect(result).to include("LLM primary architecture")
        expect(result).to include("LLM primary components")
      end

      it "emits stderr warning and falls back to static when LLM fails" do
        allow(http).to receive(:request).and_raise(SocketError, "connection refused")

        result = nil
        expect { result = described_class.generate(dir_name, analyses, primary_config) }
          .to output(/LLM unavailable for lib/).to_stderr
        expect(result).to include("Core library code")
        expect(result).to include("Modular library")
      end

      it "does not emit stderr warning when llm_primary? is false" do
        allow(http).to receive(:request).and_raise(SocketError, "connection refused")

        expect { described_class.generate(dir_name, analyses, llm_config) }
          .not_to output(/LLM unavailable/).to_stderr
      end
    end
  end
end
