# frozen_string_literal: true

require "spec_helper"
require "tmpdir"

RSpec.describe AutoDoc::Generator::SummaryGenerator do
  subject(:generator) { described_class }

  let(:dir_name) { "lib" }
  let(:config) { AutoDoc::Config.load("/tmp") }
  let(:analyses) do
    {
      "/project/lib/foo.rb" => {
        definitions: [
          { name: "Foo", type: :class, line: 1, has_doc?: true, methods: [{ name: "bar", line: 5 }] }
        ],
        imports: [
          { path: "json", type: :require }
        ],
        docs: [
          { target_name: "Foo", target_type: :class, has_summary?: true, summary: "Main application class" }
        ]
      },
      "/project/lib/utils.rb" => {
        definitions: [
          { name: "Utils", type: :module, line: 1, has_doc?: false, methods: [] }
        ],
        imports: [
          { path: "fileutils", type: :require }
        ],
        docs: []
      }
    }
  end

  describe ".generate" do
    it "returns rendered markdown with purpose text inferred from dir name" do
      result = generator.generate(dir_name, analyses, config)
      expect(result).to include("SUMMARY: lib")
      expect(result).to include("Core library code")
    end

    it "includes key components section" do
      result = generator.generate(dir_name, analyses, config)
      expect(result).to include("| Component | Type | Summary |")
      expect(result).to include("Foo")
      expect(result).to include("Utils")
    end

    it "includes architecture pattern" do
      result = generator.generate(dir_name, analyses, config)
      expect(result).to match(/Architecture Pattern/)
      expect(result).to match(/Modular/)
    end

    it "includes dependencies overview" do
      result = generator.generate(dir_name, analyses, config)
      expect(result).to include("json")
      expect(result).to include("fileutils")
    end

    it "includes links to related documents" do
      result = generator.generate(dir_name, analyses, config)
      expect(result).to include("[INDEX.md](INDEX.md)")
      expect(result).to include("[AGENTS.md](AGENTS.md)")
    end

    it "includes the generated timestamp" do
      result = generator.generate(dir_name, analyses, config)
      expect(result).to match(/Generated by auto-doc/)
      expect(result).to match(/\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}/)
    end

    context "with empty analyses" do
      let(:analyses) { {} }

      it "handles gracefully" do
        result = generator.generate(dir_name, analyses, config)
        expect(result).to include("SUMMARY: lib")
        expect(result).to include("Core library code")
        expect(result).to include("_No key components identified._")
      end
    end

    context "with custom directory name not in hardcoded list" do
      let(:dir_name) { "services" }

      it "infers purpose from directory name" do
        result = generator.generate(dir_name, analyses, config)
        expect(result).to include("SUMMARY: services")
        expect(result).to include("Services")
      end
    end

    context "with output_path provided" do
      let(:output_dir) { Dir.mktmpdir }
      let(:output_path) { File.join(output_dir, "SUMMARY.md") }

      after { FileUtils.remove_entry(output_dir) }

      it "writes the rendered content to the file" do
        generator.generate(dir_name, analyses, config, output_path: output_path)
        expect(File.exist?(output_path)).to be true
        content = File.read(output_path)
        expect(content).to include("SUMMARY: lib")
      end
    end
  end

  describe "#generate" do
    it "works with instance as well" do
      instance = described_class.new(dir_name, analyses, config)
      result = instance.generate
      expect(result).to include("SUMMARY: lib")
    end
  end
end
